// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urgnxwjmqghjrciurfyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZ254d2ptcWdoanJjaXVyZnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzI5ODQsImV4cCI6MjA2NjEwODk4NH0.qQJOBLULzwPavhSR7oktjEXJoX-WK8O-1O5DqTaT3es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);